name: kanade
description: "Android app to extract apks from installed apps."
publish_to: "none"
version: 0.5.1+8

environment:
  sdk: ">=3.0.0 <4.0.0"

scripts:
  # dart run derry build
  build: dart run build_runner build --delete-conflicting-outputs

  # dart run derry watch
  watch: dart run build_runner watch --delete-conflicting-outputs

  # dart run derry gen-i18n
  gen-i18n: flutter gen-l10n

  gen-launcher: dart run flutter_launcher_icons

  gen-splash: dart run flutter_native_splash:create

  gen-skin: dart run derry run gen-launcher && dart run derry run gen-splash

  preinstall:
    - flutter pub get
    - dart run derry run _delete_python_venv
    - dart run derry run _create_python_venv
    - dart run derry run _install_python_requirements

  _create_python_venv:
    - cd scripts/auto_translate && python -m venv venv

  _delete_python_venv:
    - dart run scripts/rm.dart scripts/auto_translate/venv

  _install_python_requirements:
    - cd scripts/auto_translate/venv/Scripts && activate && cd ../.. && pip install -r requirements.txt

  # dart run derry auto-translate
  auto-translate:
    - cd scripts/auto_translate/venv/Scripts && activate && cd ../.. && python __main__.py

  # dart run derry watch-i18n (requires npm and nodemon installed, see https://alexrintt.io/obsidian/using-nodemon-to-watch-translation-files-and-automatically-re-run-code-generation-in-flutter/)
  watch-i18n: nodemon --watch i18n --ext arb --exec "flutter gen-l10n"

dependencies:
  device_packages:
    git:
      url: https://github.com/alexrintt/device-packages
      ref: master
      path: device_packages
  dynamic_color: ^1.6.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_octicons: ^0.29.0
  flutter_shared_tools:
    git:
      url: https://github.com/alexrintt/flutter-shared-tools
      ref: master
  fluttertoast: ^8.0.8
  get_it: ^7.2.0
  injectable: ^2.3.2
  intl: ^0.18.0
  json_annotation: ^4.8.0
  material_color_utilities: ^0.5.0
  nanoid: ^1.0.0
  package_info_plus: ^3.0.1
  path: ^1.8.2
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  shared_storage:
    git:
      url: https://github.com/alexrintt/shared-storage
      ref: "91"
  string_similarity: ^2.0.0
  url_launcher: ^6.1.6
  workmanager: ^0.5.2

dev_dependencies:
  build_runner: ^2.4.7
  # See https://github.com/frencojobs/derry/issues/75
  derry:
    git:
      url: https://github.com/alexrintt/derry
      ref: main
  flutter_launcher_icons: ^0.12.0
  flutter_native_splash: ^2.2.19
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.1
  json_serializable: ^6.6.0
  lint: ^2.0.1

# Flutter Launcher Icons:
# 1. Open the android folder inside Android Studio.
# 2. Right click on the res folder and select New -> Image Asset
# 3. Select Launcher Icons (Adaptive and Legacy)
# 4. Select the path to your image and click Next

# Use this tool to generate the mipmap and the drawables automatically, but do not rely on it to configure the Android xml styles!!!
flutter_native_splash:
  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove

  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
  color: "#f0f0f0"

  # Optional parameters are listed below.  To enable a parameter, uncomment the line by removing
  # the leading # character.

  # The image parameter allows you to specify an image used in the splash screen.  It must be a
  # png file and should be sized for 4x pixel density.
  image: assets/icons/splash-light.png

  # The branding property allows you to specify an image used as branding in the splash screen.
  # It must be a png file. It is supported for Android, iOS and the Web.  For Android 12,
  # see the Android 12 section below.
  #branding: assets/dart.png

  # To position the branding image at the bottom of the screen you can use bottom, bottomRight,
  # and bottomLeft. The default values is bottom if not specified or specified something else.
  #branding_mode: bottom

  # The color_dark, background_image_dark, image_dark, branding_dark are parameters that set the background
  # and image when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above. If the image_dark parameter is specified, color_dark or
  # background_image_dark must be specified.  color_dark and background_image_dark cannot both be
  # set.
  color_dark: "#2B2D31"
  #background_image_dark: "assets/dark-background.png"
  image_dark: assets/icons/splash.png
  #branding_dark: assets/dart_dark.png

  # Android 12 handles the splash screen differently than previous versions.  Please visit
  # https://developer.android.com/guide/topics/ui/splash-screen
  # Following are Android 12 specific parameter.
  android_12:
    # The image parameter sets the splash screen icon image.  If this parameter is not specified,
    # the app's launcher icon will be used instead.
    # Please note that the splash screen will be clipped to a circle on the center of the screen.
    # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
    # 640 pixels in diameter.
    # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
    # 768 pixels in diameter.
    image: assets/icons/splash-light.png

    # Splash screen background color.
    color: "#f0f0f0"

    # App icon background color.
    icon_background_color: "#ff0000"

    # The branding property allows you to specify an image used as branding in the splash screen.
    #branding: assets/dart.png

    # The image_dark, color_dark, icon_background_color_dark, and branding_dark set values that
    # apply when the device is in dark mode. If they are not specified, the app will use the
    # parameters from above.
    image_dark: assets/icons/splash.png
    color_dark: "#2B2D31"
    icon_background_color_dark: "#00ff00"

  # The android, ios and web parameters can be used to disable generating a splash screen on a given
  # platform.
  #android: false
  ios: false
  web: false

  # Platform specific images can be specified with the following parameters, which will override
  # the respective parameter.  You may specify all, selected, or none of these parameters:
  #color_android: "#42a5f5"
  #color_dark_android: "#042a49"
  #color_ios: "#42a5f5"
  #color_dark_ios: "#042a49"
  #color_web: "#42a5f5"
  #color_dark_web: "#042a49"
  #image_android: assets/splash-android.png
  #image_dark_android: assets/splash-invert-android.png
  #image_ios: assets/splash-ios.png
  #image_dark_ios: assets/splash-invert-ios.png
  #image_web: assets/splash-web.png
  #image_dark_web: assets/splash-invert-web.png
  #background_image_android: "assets/background-android.png"
  #background_image_dark_android: "assets/dark-background-android.png"
  #background_image_ios: "assets/background-ios.png"
  #background_image_dark_ios: "assets/dark-background-ios.png"
  #background_image_web: "assets/background-web.png"
  #background_image_dark_web: "assets/dark-background-web.png"
  #branding_android: assets/brand-android.png
  #branding_dark_android: assets/dart_dark-android.png
  #branding_ios: assets/brand-ios.png
  #branding_dark_ios: assets/dart_dark-ios.png

  # The position of the splash image can be set with android_gravity, ios_content_mode, and
  # web_image_mode parameters.  All default to center.
  #
  # android_gravity can be one of the following Android Gravity (see
  # https://developer.android.com/reference/android/view/Gravity): bottom, center,
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  #android_gravity: center
  #
  # ios_content_mode can be one of the following iOS UIView.ContentMode (see
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill,
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight,
  # bottomLeft, or bottomRight.
  #ios_content_mode: center
  #
  # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
  #web_image_mode: center

  # The screen orientation can be set in Android with the android_screen_orientation parameter.
  # Valid parameters can be found here:
  # https://developer.android.com/guide/topics/manifest/activity-element#screen
  #android_screen_orientation: sensorLandscape

  # To hide the notification bar, use the fullscreen parameter.  Has no effect in web since web
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom, SystemUiOverlay.top]);
  # fullscreen: true

  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s)
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: Roboto Mono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
          weight: 700
    - family: Inconsolata
      fonts:
        - asset: assets/fonts/Inconsolata-Regular.ttf
          weight: 700
    - family: Forward
      fonts:
        - asset: assets/fonts/Forward.ttf
    - family: Zen Kaku Gothic Antique
      fonts:
        - asset: assets/fonts/ZenKakuGothicAntique-Regular.ttf
